# This is a basic workflow to help you get started with Actions

name: Compile LaTeX to PDF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            nime-paper-template.tex
            nime-music-workshop-template.tex
          work_in_root_file_dir: true
      - name: Upload paper file
        uses: actions/upload-artifact@v4
        with:
          name: nime-paper
          path: nime-paper-template.pdf
      - name: Upload music file
        uses: actions/upload-artifact@v4
        with:
          name: nime-music
          path: nime-music-workshop-template.pdf
